version: '3.9'

services:
  mssql_db:
    container_name: hospital-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    restart: unless-stopped